### ISSUE TITLE
body-parser deprecation warning

### ISSUE THREAD

**Issue by jinoru** [sgnn7/deploying_with_docker#5]
Using Ubuntu 16.04,
I'm at the `npm start` step. The js application won't start outputting to console,
`body-parser deprecated undefined extended: provide extended option index.js:21:20
current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.`

Is there some portion I haven't installed correctly? or is this a correction I should make in the js?

**Comment by sgnn7** [comment]
Hey @jinoru,
I'll take a look over the weekend. Have you made sure that you have [this](https://github.com/sgnn7/deploying_with_docker/commit/db76e3e099825ca98d9ec59ca132966ba4d5954a) change ([parent issue](https://github.com/sgnn7/deploying_with_docker/issues/2)) applied since the upstream module changed after the book was printed?

**Comment by jinoru** [comment]
Yes, I've implemented that change.

**Comment by sgnn7** [comment]
@jinoru Can you let me know what page of the book you're on as well ?  I'm trying to figure out which section you're working on since these are reused a few times and I forgot to ask yesterday.

**Comment by sgnn7** [comment]
@jinoru Fix is applied - [these](https://github.com/sgnn7/deploying_with_docker/commit/d43114ed4804f651dbbcda72ee5ad397520bb864) are the exact changes you need. Do you mind testing it out?
